server:
  shutdown: graceful
  port: 8080
spring:
  cache:
    type: redis
  autoconfigure:
    exclude:
  lifecycle:
    timeout-per-shutdown-phase: 5m
  data:
    redis:
      host: redis-1-service
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-1-service:3306/msa_prod?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: lldjlocal
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
logging:
  level:
    com.ll: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.web.cors: INFO
custom:
  site:
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
  temp:
    dirPath: /tmp
  genFile:
    dirPath: /gen